<a href="https://colab.research.google.com/github/aageo25/aageo25/blob/main/computational_graphs_and_linear_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `autograd`

In [1]:
import torch
a = torch.tensor([[1,2,3],[4,5,6]], requires_grad=True, dtype=torch.float)
b = a+2
c = 2*b*b
out = c.mean()
out.backward() # calculates the derivative of the previous operation
print(a.grad)

tensor([[2.0000, 2.6667, 3.3333],
        [4.0000, 4.6667, 5.3333]])


In [3]:
print(a.detach().requires_grad) # detach prevents further tracking of operations and detaches the tensor from the tracking history

False


In [6]:
# error if we detached, but still needs to calculate gradients
a = torch.ones((2,3), requires_grad=True)
b = a + 2
c = 2*b*b
out = c.mean()
out.backward(retain_graph=True) # avoids pytorch to cread a new computational graph
print(a.grad)
out.backward()
print(a.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])


# Linear models

## Linear regression